---
abstract: 'Forth Interpreter with a Pegex Compiler'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  Capture::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pegex-Forth
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Pegex: '0.40'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/pegex-forth-pm/issues
  homepage: https://github.com/ingydotnet/pegex-forth-pm
  repository: https://github.com/ingydotnet/pegex-forth-pm.git
version: '0.06'
